### PR TITLE
Cannot shuffle variables in quantifier list if polymorphic

### PR DESCRIPTION
**Pull request by ibnyusuf**
Polymorphism requires that type variables appear in the quantifier list befoere term variables, as the type of the term variables may refer to previously declared type variables.

Also added a couple of polymorphic problems to sanity check to hopefully reduce the number of breaking changes that we are seeing.

### CODE REVIEW

**Review by MichaelRawson — APPROVED** [review]
Sounds like a good fix - however, I wonder if this isn't too aggressive, killling some of the shuffling goodness - what do you think, @quickbeam123?

Would it be possible to shuffle the sort and term variables separately, or maybe even better have rectification split such dependent quantifiers?

**Comment by quickbeam123** [comment]
As a quick fix, it looks like a reasonable way of avoiding a problem.

As an opportunity to learn a lesson and use it while striving for an overall better design, let's brainstorm:
- we already had https://github.com/vprover/vampire/issues/421
- there I wrote "But flattening comes and merges the two blocks togeter. However, modifying flattening is not the right fix, since the user can already write them merged."
- here we see one such merged one: `! [B: $tType,A: $tType,G: fun(A,B),F: fun(A,B)] :`
- would it be nice to live in a world where type variables and normal (first-order) quantifiers always live in different blocks? (Shouldn't we mandate this also for TPTP?)
- how important is the intuition that in a single block, quantification order does not matter
(intuitively, I find it quite important. The shuffling code relies on it)

How hard would it be, to make rectification do it? (Can we always have {all the types first} {then rest follows}?) Was I right that it's actually flattening that's happy to undo it? (Do we always apply them in a specific favourable order, for this to work?)

**Review by quickbeam123 — APPROVED** [review]

**Comment by ibnyusuf** [comment]
I agree that keeping type variable quantifiers and term variable quantifiers separate is a good idea. Not sure about the best way to implement (make them syntactically different things? Add a check in flattening to make sure we don't undo this separation?)

**Review by joe-hauns — APPROVED** [review]
Sounds all good to me. Don't have too much of an opinion about what's happening before clausification as I don't have a proper understanding of the codebase pre-saturation. But looks and sounds all good :)

**Pull request merged**
