### PR TITLE
Updates for Question Answering

### PR DESCRIPTION
**Pull request by selig**
This pull request has been created to view the changes to question answering in this old branch. It might get merged if those changes look okay.

### CODE REVIEW

**Comment by quickbeam123** [comment]
Is this fixing Uwa at the same time?

**Comment by selig** [comment]
No, the part fix got included in my rebase by mistake. I’ll finish fixing that separately. Giles

Sent from my iPhone

On 31 Mar 2020, at 18:43, Martin Suda <notifications@github.com> wrote:

﻿

Is this fixing Uwa at the same time?

**Comment by logicReasoner** [comment]
What is the current status of this functionality? 
Additionally, can Vampire be made to return all (more than one found answer) when using the `-qa` option? Currently it seems to return just one (the first found?) answer.
Thanks in advance!

**Comment by selig** [comment]
Great question. I should finish it. This branch incorporates some experimental things related to question answering (explored in this paper https://easychair.org/publications/paper/5L6q) and my plan was to tidy them up. This will be easier with a 'customer' prodding me...

This branch introduces a new  option "question_count" (bad name, I'll change that) that limits the number of answers. By default it will continue returning answers whilst it can still find them (different from master where it terminates on the first answer). But note that the way that Vampire works it will currently return a lot of duplicates - the plan is to filter these out. This branch also fails to notice when there are an identifiably finite set of answers e.g. it will always say that there may be more. Again, something that could be fixed in some cases but is not yet.

Do you have any question answering related feature requests?

**Comment by logicReasoner** [comment]
@selig Your plan sounds great! 
As a final addition maybe something like the following option implemented by the E prover could be useful:
```
--conjectures-are-questions
    Treat all conjectures as questions to be answered. This is a wart
    necessary because CASC-J6 has categories requiring answers, but does not
    yet support the 'question' type for formulas.
```

**Comment by selig** [comment]
@logicReasoner This is actually already an undocumented feature... kind of. Vampire doesn't distinguish between the conjecture and question role. In question answering mode any existential  conjecture or question will be treated as a question. I can't remember if we have support for multiple questions (we don't support multiple conjectures).

**Comment by MichaelRawson** [comment]
This is quite a long-standing merge! With respect to @hzzv's changes in #442, does this still make sense? If so, how much effort is it to get this merged, @selig?

**Comment by MichaelRawson** [comment]
Closing for lack of activity, feel free to re-open if not in fact dead.

**Pull request closed without merging**
