### PR TITLE
add -Wall to CMake

### PR DESCRIPTION
**Pull request by MichaelRawson**
Add "all warnings" in GCC/Clang and compile cleanly with them. Bonus: remove some unused private member variables.

### CODE REVIEW

**Comment by MichaelRawson** [comment]
Actually this needs to work for release builds as well.

**Comment by quickbeam123** [comment]
I am guessing this is a work in progress, right?

**Comment by MichaelRawson** [comment]
Yeah sorry, forgot to test the release build.

**Comment by MichaelRawson** [comment]
@quickbeam123 - if you're willing this one's ready to go as well. I think GCC probably has some gripes as well, I'll deal with that separately.

**Pull request merged**
