### PR TITLE
set kbo weights of fool constants to 1 no matter the weight scheme

### PR DESCRIPTION
**Pull request by quickbeam123**
Fixes https://github.com/vprover/vampire/issues/557

### CODE REVIEW

**Review by MichaelRawson — APPROVED** [review]
Seems sensible.

**Comment by joe-hauns** [comment]
Why/in which rule do we need the property that `$false` is least? Can we just make saturation incomplete when the fool constant weight is not 1 and the respective options are enabled?

**Comment by quickbeam123** [comment]
In FOOL paramodulation, I believe. What you suggest is also a possibility...

**Comment by joe-hauns** [comment]
I see. I missed the crutial option `-foolp`... 
I think we still need to make the saturation incomplete if a user sets `_foolConstant` to something different to `1` using the weight setting file, right?

**Review by mezpusz — APPROVED** [review]

**Comment by quickbeam123** [comment]
I tried not to follow the path for making _foolConstant settable from a file, but maybe it's possible somehow?

In any case, I think the file input is so rare that working on a robust way of figuring out completeness for user-specified weight scheme and precedence might not be worth the effort. Unless it's already there and a one-liner would fix it?

**Pull request merged**
