### PR TITLE
Fixing FMB Issues

### PR DESCRIPTION
**Pull request by selig**
This PR fixes FMB issues 134, 252,  302, and 303 and adds some more assertions to FMB to catch further issues if they exist.

### CODE REVIEW

**Comment by quickbeam123** [comment]
@selig , could you please check on your side this is not changing the version of z3?

**Comment by selig** [comment]
@quickbeam123 (and  @MichaelRawson) thanks for noticing I've (yet again)  accidentally updated the z3  version. I'm not sure why this keeps happening and I don't know how to fix it. I try checking out the version from master and adding it but then git things I haven't got any new changes to commit

`(base) Giless-MacBook-Pro:vampire giles$ git checkout master -- z3
(base) Giless-MacBook-Pro:vampire giles$ git  status -uno
On branch fmb_fixes
Your branch is up to date with 'origin/fmb_fixes'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   z3

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   z3 (new commits)

Untracked files not listed (use -u option to show untracked files)
(base) Giless-MacBook-Pro:vampire giles$ git  add z3
(base) Giless-MacBook-Pro:vampire giles$ git  status -uno
On branch fmb_fixes
Your branch is up to date with 'origin/fmb_fixes'.

nothing to commit (use -u to show untracked files)`

I'm pretty certain I never touched z3 after branching from master in the first place.

**Comment by MichaelRawson** [comment]
No problem @selig , I can look at it this eveningv and add something to the instructions. 🙂 `git-submodule` semantics are a bit weird because it has to pretend to be a file (just a revision number) and a whole checked-out repository.

In the meantime think if you remove the whole directory and then checkout the version from master that should work.

**Comment by quickbeam123** [comment]
I could create an updated/cleaned version of this branch -- see `fmb_fixes_noZ3` -- by three applications of `git cherry-pick -n`. (`-n` is for `--no-commit`).

The z3 modifying commit (which I had to partially restore) was the middle one. And it was putting z3 to 
```
commit 39af2a188da198b87037fe4fad2bd5da67386c86 (HEAD, tag: z3-4.8.11)
Author: Nikolaj Bjorner <nbjorner@microsoft.com>
Date:   Fri Jun 4 15:54:19 2021 -0700
```

**Comment by quickbeam123** [comment]
I could also use your `git checkout master -- z3` to crate a fix here. (Although, I would prefer using for master the version where we don't switch z3 back and forth.)

I think the main source of confusion in general is that the information about z3 being modified from the perspective of vampire, such as in:
```
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   z3
```
or
```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   z3 (new commits)
```
should be confronted with what's the actual content of the z3 folder at that point.

I think the z3 folder content won't move unless one does `git submodule update` or related, but various commits of vampire may report `modified: z3` if they "wished" the content of the z3 folder was different from their perspective.

By the way, master is currently happy when the context of z3 folder is
```
commit f03d756e086f81f2596157241e0decfb1c982299 (HEAD)
Author: Nikolaj Bjorner <nbjorner@microsoft.com>
Date:   Wed Aug 25 06:34:27 2021 -0700
```

**Comment by selig** [comment]
Thanks! Are you happy to merge?

**Comment by quickbeam123** [comment]
Happy now! I will use the PR after all (the cherry-picked commits steal your authorship).

**Pull request merged**
