### PR TITLE
remove `STLAllocator<T>`

### PR DESCRIPTION
**Pull request by MichaelRawson**
With the re-work of `Allocator`, it's possible that `STLAllocator<T>` is no longer necessary either. This *could* have a performance impact as it calls into Vampire's small-object allocator, but I suspect it might be minimal or positive and @quickbeam123 was keen on the idea of no more `vstring`.

This is just the initial sketch: if it passes the performance question, I will clean up further.

### CODE REVIEW

**Comment by MichaelRawson** [comment]
Tag #157.

**Comment by quickbeam123** [comment]
Preliminary run shows this is measurably worse. (Could this be because of `vstring` though?) Maybe we should figure out which class of those affected is a least a bit hot and keep the special treatment only that one?

**Comment by MichaelRawson** [comment]
Bleh - it wasn't noticeably bad on the few things I tested here, so I hoped otherwise! I'll dig into it and do exactly that, it'd be nice to have this gone.

**Comment by quickbeam123** [comment]
Measurable means "5" problems over the whole TPTP in -i 100000. But still, I'd consider this an opportunity to dig deeper.

**Comment by MichaelRawson** [comment]
Is it easy to work out which those 5 problems are? `perf diff` is saying that this Vampire calls `memset` a lot more from `MLMatcher`, but I'm not really sure why or what to do with this information.

**Comment by quickbeam123** [comment]
The 5 extra was actually 42 gained / 37 lost for the default strategy, i.e., with lrs. Will better come back (in a while) with a discount-based diff.

**Comment by quickbeam123** [comment]
No problem in the diff for discount. Sorry for the false alarm. I think this can be promoted to the full extent. 

Except maybe for the vstring, maybe we can keep it as a typedef to prevent another giant refactor?

**Comment by MichaelRawson** [comment]
Great! I'll eliminate most of this properly then. Agreed with `vstring`. :-)

**Comment by MichaelRawson** [comment]
Should be ready for re-review. `v(i|o)?stringstream` and various `vcontainers` are no more, only `vstring` remains. `vvector` was a bit of a pain but is now also dead.

**Comment by MichaelRawson** [comment]
As discussed, also inline `vstring`.

**Pull request merged**
