### PR TITLE
Minisat/utils/System.*: use fpu_control only on glibc

### PR DESCRIPTION
**Pull request by xgqt**
Signed-off-by: Maciej Barć <xgqt@gentoo.org>

### CODE REVIEW

**Comment by MichaelRawson** [comment]
Hi Maciej - thanks for the patch! The [Minisat](http://minisat.se/) in Vampire is vendored/hacked around a bit, you might want to check upstream too.

Out of curiosity, what brought you here? Are we packaged in Gentoo?

@quickbeam123 - looks fine to me, should be a quick merge.

**Review by MichaelRawson — APPROVED** [review]

**Comment by xgqt** [comment]
> 

> Hi Maciej - thanks for the patch! The Minisat in Vampire is vendored/hacked around a bit, you might want to check upstream too.

In Gentoo we use https://github.com/stp/minisat, but yes, it suffers the same issue, I lost the bug notification for that (https://bugs.gentoo.org/832519).

> Out of curiosity, what brought you here? Are we packaged in Gentoo?

Yes, I'm on a mission to get some popular theorem provers into Gentoo repo. :D

**Comment by MichaelRawson** [comment]
>Yes, I'm on a mission to get some popular theorem provers into Gentoo repo. :D

Hey, that's great news! Please do let us know about other portability problems, I can't promise that we'll fix them but it'd be good to hear about them at least. Thanks for the packaging effort.

I expect this to be merged reasonably soon, but we don't move as fast as Minisat around here!

**Comment by xgqt** [comment]
Ping. `stp/minisat` merged the fix already.

**Comment by xgqt** [comment]
Thanks!

**Pull request merged**
