### PR TITLE
since tryParseTPTP tries to only throw TPTP::ParseErrorException, ...

### PR DESCRIPTION
**Pull request by quickbeam123**
..., that's what we should be catching to retry with tryParseSMTLIB2

### CODE REVIEW

**Comment by quickbeam123** [comment]
Until now we had:

```
./vampire ../../sledgehammer-eval/problem-examples/Core_DOM/SMT2/0023_Core_DOM_Functions/prob_01627_079330__15026148.smt_in
% Running in auto input_syntax mode. Trying TPTP
Parsing Error on line 1
Bad character at position 0
```

without a retry (we go for TPTP first, because of the non-standard file extension `smt_in`).

**Comment by selig** [comment]
Great catch and I agree with your change but I noticed we're also missing exceptions from the SMT parser (from the lexer and parser, which are the ones we'd expect to hit if we have a TPTP file).

My proposed solution works around the fact that the various exceptions involved here are a bit of a mess!

**Comment by quickbeam123** [comment]
Since we are at this, would it be too bad to just catch ANY exception (instead of a potentially open eded list and a templated call)? 

Alternatively, a common ancestor (in the class hierarchy) of all the parsing exceptions?

**Comment by selig** [comment]
I think with ANY exception we still need the templated call. I tried to look for a suitable common ancestor and it didn't work but that might be my C++ fu failing. Just using Lib::Exception ended up with the wrong cry function being called. It's important we show the user the output of the failing exception when skipping it.

**Comment by quickbeam123** [comment]
I see. A general exception cannot not cry! :)

**Pull request merged**
