### PR TITLE
Theory of bitvectors

### PR DESCRIPTION
**Pull request by quickbeam123**

### CODE REVIEW

**Comment by Columpio** [comment]
Could you please describe a status of this PR? Does it already work for simple BV formulas?

**Comment by quickbeam123** [comment]
It could parse BV formulas, simplify constant expressions and supply some reasonable axioms about bitvectors when needed.

See: https://ieeexplore.ieee.org/document/9049847

The main problem with this PR is that it's almost three years behind the developments in master.

**Comment by quickbeam123** [comment]
Did you try clicking, on the webpage, on the "PDF" sticker at bottom right? 

https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9049847&casa_token=6UuVatOl5XcAAAAA:RhSWf1NTLd_-ptSB5mMYRvQrCxFKlKpEvI8YlzpFSXIWOK8i2sPCo-MHo_QRbe8uBppCQNP_LYE 

Or putting the paper's title into google? ;)

https://zenodo.org/record/4543086

**Comment by MichaelRawson** [comment]
@quickbeam123 - what are we going to do about this one? If it's semi-reasonable to make it work, we can do that. Otherwise let's do what I suggested in #48, close this and "archive" the branch for posterity/a future reimplementation.

**Comment by quickbeam123** [comment]
Close and archive sounds great! The branch will serve as a good guide to what needs to be done for some basic BV functionality. But as this was a master's project, I guess an experienced vampirist could reimplement things from scratch probably as fast as it would take to make this work with master again...

**Pull request closed without merging**
