### PR TITLE
Fix hidden overloaded virtual function warning in AnswerExtractor

### PR DESCRIPTION
**Pull request by mezpusz**
Just renaming a function that apparently hides a virtual one, according to my clang. Also, I removed the `virtual` keyword since the function called is not virtual either, but I'm okay with leaving it if it is needed.

### CODE REVIEW

**Review by MichaelRawson — APPROVED** [review]
Sensible. Will wait for @hzzv 's approval, but after that will merge.

**Comment by quickbeam123** [comment]
This might be related to something I didn't really understand in the synthesis PR. 

There:
@hzzv made `TermList  TermTransformer::transform(TermList ts);` virtual, @MichaelRawson asked "Oh, this is fun. Did nobody override this before?!" and the reply was "Apparently not :)".

Do you guys remember what this was all about and how does it relate to @mezpusz's fix?

**Comment by MichaelRawson** [comment]
So there's `TermTransformer::transform(TermList)`, which after the synthesis PR is dynamically-dispatched because `ConjectureSkolemReplacement` overloads it. This seems to be the intended behaviour, quoting from `TermTransformer.hpp`

```
 * The inheriting class implemets function transform(TermList)
 * and then the function transform(Literal*) uses it to transform subterms
 * of the given literal.
```

I'm not sure _how_ this worked before, hence my confusion in that review comment.

But here there is a name clash on `transform(Literal *)`, but I don't think the intention is to override it, just call the base class' version. So probably it should go all together?

**Comment by MichaelRawson** [comment]
https://godbolt.org/z/9jr8qPMr5 - weirdly, name lookup seems to be broken with virtual and non-virtual functions with the same name. @mezpusz seems to have the smallest-diff fix, though in the long run we should probably rename `TermTransformer::transform(Literal *)`. I think `TermTransformer` is on the way out though (?), in favour of `BottomUpEvaluation`, see #376.

**Comment by quickbeam123** [comment]
OK, so I changed this completely.
1) There is a different fix in AsnwerExtractor.hpp (I think a bit more c++ hardcore-ish, but it teaches a lesson.)
2) I fixed/added comments into TermTransformer.hpp fixing the typo there
3) streamlined `TermTransformer::transform(TermList ts)` (@MichaelRawson , could you please check whether you agree?)
4) went pedantic about using `override` 

The last question that I have is for @hzzv: Do you, by any chance, remember why you had to override `transform(TermList ts)` in `ConjectureSkolemReplacement`? I understand it does not the same thing as the base class's variant. But then again, I think it only needs to be called if there is FOOL in the input (There was no `TermList transform(TermList ts);` in `TermTransformer` until @aztek extended it for FOOL processing. I don't think the main function `TermTransformer::transform(Term* term)` only indirectly via `TermTransformer::transformSpecial`. Does it mean you had to mix ConjectureSkolemReplacement and FOOL?)

**Comment by MichaelRawson** [comment]
>streamlined TermTransformer::transform(TermList ts) (@MichaelRawson , could you please check whether you agree?)

Looks good to me - shorter and pretty sure that should have zero/positive perf impact.

**Review by hzzv — APPROVED** [review]
Thanks for checking with me! It looks good to me (and I also confirmed it doesn't change the functionality for synthesis).

@quickbeam123 - yes, `ConjectureSkolemReplacement` creates FOOL terms. Its output is the program we're synthesizing, and can thus contain if-then-elses, where the conditions are formulas.

**Comment by quickbeam123** [comment]
OK, but then I want to suggest we stick with Petra's version for the parent class too!

I just went through all the child classes and none of them (I believe), except ConjectureSkolemReplacement, is ever running on non-shared/special/fool terms. So it should not matter for those, and ConjectureSkolemReplacement will be relieved of its override.

Unless you protest, I will change things and simply this PR further.

**Comment by quickbeam123** [comment]
@hzzv , @MichaelRawson , could you give this one extra check, please?

**Comment by MichaelRawson** [comment]
I'm happy. Took a little while, but we got there in the end! This looks nice as a final solution. :-)

**Comment by hzzv** [comment]
I agree with Michael! And yes, it works for synthesis :)

**Comment by quickbeam123** [comment]
Thank you!

**Pull request merged**
