### PR TITLE
Reorganising HOL options

### PR DESCRIPTION
**Pull request by ibnyusuf**
- Added a new tag `HIGHER_ORDER` to the option tags and reclassified all higher-order options with this tag
- Reorganised the Options.cpp file to bring the various higher-order options together

### CODE REVIEW

**Comment by quickbeam123** [comment]
I know the warning message (and now also the tag) are already there, but could you possibly find a more discriminating name for `superposition`?

**Comment by ibnyusuf** [comment]
Do you mean something that makes it stand out as being linked to HOL? Whatabout `superposition_hol`?

**Comment by quickbeam123** [comment]
Yes. `superposition_hol` would sure work!

**Comment by ibnyusuf** [comment]
Renamed

**Pull request merged**
