### PR TITLE
Fix forward subsumption resolution

### PR DESCRIPTION
**Pull request by JakobR**
The current version may miss some inferences.

### CODE REVIEW

**Comment by quickbeam123** [comment]
Jakob, you are now the leading expert on this part of the codebase so I would trust your update.

Maybe, before we do the merge, do you think this could benefit from some testing?

**Comment by JakobR** [comment]
Yes, we should definitely do some checks first. (Let's put this PR on hold until we're done with them.)

**Comment by selig** [comment]
Hi @JakobR do you think this is something we should aim to get in before competitions or keep on hold until afterwards?

**Comment by JakobR** [comment]
Since it's "just" a completeness issue (and apparently didn't cause noticable trouble so far), I would prefer to keep it on hold for now.

**Comment by quickbeam123** [comment]
Hi @JakobR, could this be now revived and merged? I am just starting a quick test!

**Comment by quickbeam123** [comment]
This looks like a clear improvement! 

Especially:
`./vampire -sa discount -awr 10 -fsd on Problems/SYO/SYO679-1.p`
becomes much easier thanks to this!

**Pull request merged**
