### PR TITLE
Fix quotientE for fractional numbers

### PR DESCRIPTION
**Pull request by joe-hauns**
Fixes the behaviour of quotientE. 
The previous implementation did not correspond to the semantics specified by TPTP for Rationals and Reals.

Further some unit tests are added.

### CODE REVIEW

**Comment by selig** [comment]
@quicquid are you able to run a test on this? It looks sensible but last time we made a sensible update to this stuff we broke it.

**Comment by quickbeam123** [comment]
Do we know of an example where quotient_{e,t,f} / remainder_{e,t,f} are used on $rat or $real? Not sure if the TPTP specification truly thought about this, ... the whole idea of trying to give meaning to integer division of non-integer numbers seems a bit silly to me.

**Comment by joe-hauns** [comment]
This was exactly what I thought as well. I grepped for {`quotient`,`remainder`}`_`{`t`,`e`,`f`} , in all of tptp and there's only one file where any of them is used in a non-integral context: `SYN/SYN000=2.p`. i.e. all of them are used in rat&real contexts there. The snipped:
```
...
tff(quotient_e_int,axiom,(
    p_int($quotient_e(3,3)) )).

tff(quotient_e_rat,axiom,(
    p_rat($quotient_e(3/9,3/9)) )).

tff(quotient_e_real,axiom,(
    p_real($quotient_e(3.3,3.3)) )).

tff(quotient_t_int,axiom,(
    p_int($quotient_t(3,3)) )).

tff(quotient_t_rat,axiom,(
    p_rat($quotient_t(3/9,3/9)) )).

tff(quotient_t_real,axiom,(
    p_real($quotient_t(3.3,3.3)) )).

tff(quotient_f_int,axiom,(
    p_int($quotient_f(3,3)) )).

tff(quotient_f_rat,axiom,(
    p_rat($quotient_f(3/9,3/9)) )).

tff(quotient_f_real,axiom,(
    p_real($quotient_f(3.3,3.3)) )).

tff(remainder_e_int,axiom,(
    p_int($remainder_e(3,3)) )).

tff(remainder_e_rat,axiom,(
    p_rat($remainder_e(3/9,3/9)) )).

tff(remainder_e_real,axiom,(
    p_real($remainder_e(3.3,3.3)) )).

tff(remainder_t_int,axiom,(
    p_int($remainder_t(3,3)) )).

tff(remainder_t_rat,axiom,(
    p_rat($remainder_t(3/9,3/9)) )).

tff(remainder_t_real,axiom,(
    p_real($remainder_t(3.3,3.3)) )).

tff(remainder_f_int,axiom,(
    p_int($remainder_f(3,3)) )).

tff(remainder_f_rat,axiom,(
    p_rat($remainder_f(3/9,3/9)) )).

tff(remainder_f_real,axiom,(
    p_real($remainder_f(3.3,3.3)) )).
...
```
Even if we remove the  {`quotient`,`remainder`}`_`{`t`,`e`,`f`}_{`rat`,`real`} axioms current master can find a proof in default mode within 0.098 s. So we could potentially get rid of evaluating these pretty unintuitive functions (and therefore get rid of the mess of having 4 different divisions per fractional type ;) )..

**Comment by quickbeam123** [comment]
I am in favour of pretending we (=vampire) don't understand {quotient,remainder}_{t,e,f}_{rat,real} and simply not evaluating them at all. And simplifying the code correspondingly.

**Pull request merged**
