### PR TITLE
Remove "summary" from file headers

### PR DESCRIPTION
**Pull request by hzzv**
This PR removes the "summary" paragraph from the header of all files that contained it.

### CODE REVIEW

**Comment by selig** [comment]
Thanks!


 @quickbeam123 please don't merge yet as I need to add a couple of files.

**Comment by selig** [comment]
@hzzv  Could you post the script you used for this on Slack so that it can be applied to pull requests still using the old header.

**Comment by MichaelRawson** [comment]
@selig - while you're at it, is there a reason for the blank line at the top of (all) source files?

**Comment by selig** [comment]
@MichaelRawson I'm guessing this is a side-effect of the script I wrote to add the headers.

**Comment by hzzv** [comment]
@selig Which Slack channel should I post the script to?

**Pull request merged**
